      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.GPORTAL_FTP_HOST }}
          username: ${{ secrets.GPORTAL_FTP_USER }}
          password: ${{ secrets.GPORTAL_FTP_PASS }}
          protocol: ftps
          port: 34831
          local-dir: ./to-upload/
          server-dir: /Server/
          dangerous-clean-slate: false
          exclude: |
            **/.git*
            **/.github/**
            **/README*
            **/*.ps1
            **/Saves/**
            **/Logs/**
            **/db/**
            **/Workshop/**
